"""Buyer matching engine — pgvector ANN + credibility-weighted reranking."""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

import structlog
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from matching_service.infrastructure.embeddings.sentence_transformer import get_embedder

log = structlog.get_logger(__name__)


@dataclass
class MatchRequest:
    product_id: str
    product_description: str
    hs_code: str | None
    moq: int
    top_k: int = 10
    country_filter: list[str] | None = None


@dataclass
class BuyerMatch:
    buyer_id: str
    name: str
    country: str
    hs_codes: list[str]
    credibility_score: float
    similarity_score: float
    distance: float
    explanation: str
    is_synthetic: bool
    min_order_qty: int = 0


class MatchingService:
    """
    Pipeline:
      1) Load product embedding from product_embedding (generated by embedding-worker)
      2) pgvector ANN search via <=> (cosine distance)
      3) Apply metadata filters (HS code, country, MOQ)
      4) Final score = 0.7 × similarity + 0.3 × credibility
      5) Generate Indonesian explanation per match
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def find_buyers(self, request: MatchRequest) -> list[BuyerMatch]:
        log.info("matching.search.start", product_id=request.product_id, top_k=request.top_k)

        embedding = await self._ensure_product_embedding(request.product_id)
        if embedding is None:
            log.warning("matching.no_embedding", product_id=request.product_id)
            return []

        rows = await self._ann_search(embedding, request)
        results = [self._enrich(r) for r in rows][: request.top_k]
        log.info("matching.search.done", product_id=request.product_id, found=len(results))
        return results

    async def find_buyers_by_embedding(
        self,
        embedding: list[float],
        top_k: int = 10,
        country_filter: list[str] | None = None,
        min_volume: int | None = None,
        category: str | None = None,
    ) -> list[BuyerMatch]:
        """ANN search using a supplied embedding vector with optional metadata filters."""
        log.info("matching.embedding_search.start", top_k=top_k, filters={
            "country": country_filter, "min_volume": min_volume, "category": category,
        })
        rows = await self._ann_search_by_embedding(
            embedding,
            top_k,
            country_filter=country_filter,
            min_volume=min_volume,
            category=category,
        )
        results = [self._enrich(r) for r in rows][:top_k]
        log.info("matching.embedding_search.done", found=len(results))
        return results

    async def _load_product_embedding(self, product_id: str) -> list[float] | None:
        result = await self._session.execute(
            # Cast to text so asyncpg always returns a plain string regardless
            # of whether the pgvector codec is registered — avoids the
            # list(str) → list-of-chars pitfall when codec is absent.
            text("SELECT embedding::text FROM product_embedding WHERE product_id = :pid"),
            {"pid": product_id},
        )
        row = result.fetchone()
        return json.loads(row[0]) if row else None

    async def _ensure_product_embedding(self, product_id: str) -> list[float] | None:
        """Return the product embedding, generating + caching it on-demand if the
        async embedding job has not produced one yet. Guarantees matching works as
        soon as a product exists, not only after the background embedder runs."""
        emb = await self._load_product_embedding(product_id)
        if emb is not None:
            return emb

        row = (
            await self._session.execute(
                text("SELECT name, description FROM product WHERE id = :pid"),
                {"pid": product_id},
            )
        ).fetchone()
        if row is None:
            return None
        src = f"{row[0] or ''}. {row[1] or ''}".strip(". ").strip()
        if not src:
            return None

        log.info("matching.embed_on_demand", product_id=product_id)
        embedder = get_embedder()
        vec = embedder.embed_sync([src])[0]

        # Cache for subsequent searches (best-effort — never fail the match on a write error).
        try:
            await self._session.execute(
                text(
                    """
                    INSERT INTO product_embedding (product_id, model, embedding, created_at, updated_at)
                    VALUES (:pid, :model, CAST(:emb AS vector), NOW(), NOW())
                    ON CONFLICT (product_id)
                    DO UPDATE SET embedding = CAST(:emb AS vector), model = :model, updated_at = NOW()
                    """
                ),
                {"pid": product_id, "model": embedder.model_name, "emb": str(vec)},
            )
            await self._session.commit()
        except Exception as exc:  # noqa: BLE001
            log.warning("matching.embed_cache_failed", product_id=product_id, exc=str(exc))
            await self._session.rollback()
        return vec

    async def _ann_search(
        self,
        query_embedding: list[float],
        request: MatchRequest,
    ) -> list[dict[str, Any]]:
        params: dict[str, Any] = {
            # asyncpg needs the vector as a string '[x, y, ...]', not a Python list.
            "q": str(query_embedding),
            "k": request.top_k * 3,  # over-fetch for post-filter
        }
        hs_clause = ""
        country_clause = ""
        if request.hs_code:
            hs_clause = "AND :hs_code = ANY(b.hs_codes)"
            params["hs_code"] = request.hs_code
        if request.country_filter:
            country_clause = "AND b.country = ANY(:countries)"
            params["countries"] = request.country_filter

        sql = text(f"""
            SELECT
                b.id              AS buyer_id,
                b.name            AS name,
                b.country         AS country,
                b.hs_codes        AS hs_codes,
                b.credibility_score AS credibility_score,
                b.is_synthetic    AS is_synthetic,
                b.min_order_qty   AS min_order_qty,
                (be.embedding <=> :q) AS distance
            FROM buyer_embedding be
            JOIN buyer b ON b.id = be.buyer_id
            WHERE b.is_active = TRUE
                {hs_clause}
                {country_clause}
            ORDER BY be.embedding <=> :q
            LIMIT :k
        """)
        rows = (await self._session.execute(sql, params)).mappings().all()
        return [dict(r) for r in rows]

    async def _ann_search_by_embedding(
        self,
        query_embedding: list[float],
        top_k: int,
        *,
        country_filter: list[str] | None = None,
        min_volume: int | None = None,
        category: str | None = None,
    ) -> list[dict[str, Any]]:
        params: dict[str, Any] = {
            "q": str(query_embedding),
            "k": top_k * 3,
        }
        clauses: list[str] = []
        if country_filter:
            clauses.append("AND b.country = ANY(:countries)")
            params["countries"] = country_filter
        if min_volume is not None:
            clauses.append("AND b.min_order_qty >= :min_volume")
            params["min_volume"] = min_volume
        if category:
            clauses.append(
                "AND EXISTS (SELECT 1 FROM unnest(b.hs_codes) hs WHERE hs LIKE :cat_prefix)"
            )
            params["cat_prefix"] = f"{category}%"

        where_extra = "\n                ".join(clauses)
        sql = text(f"""
            SELECT
                b.id              AS buyer_id,
                b.name            AS name,
                b.country         AS country,
                b.hs_codes        AS hs_codes,
                b.credibility_score AS credibility_score,
                b.is_synthetic    AS is_synthetic,
                b.min_order_qty   AS min_order_qty,
                (be.embedding <=> :q) AS distance
            FROM buyer_embedding be
            JOIN buyer b ON b.id = be.buyer_id
            WHERE b.is_active = TRUE
                {where_extra}
            ORDER BY be.embedding <=> :q
            LIMIT :k
        """)
        rows = (await self._session.execute(sql, params)).mappings().all()
        return [dict(r) for r in rows]

    def _enrich(self, raw: dict[str, Any]) -> BuyerMatch:
        distance = float(raw["distance"])
        similarity = 1.0 - distance
        credibility = float(raw["credibility_score"])
        # Final score: 70% similarity + 30% credibility
        final = (similarity * 0.7) + (credibility * 0.3)
        return BuyerMatch(
            buyer_id=str(raw["buyer_id"]),
            name=raw["name"],
            country=raw["country"],
            hs_codes=list(raw["hs_codes"]),
            credibility_score=round(credibility, 3),
            similarity_score=round(final, 4),
            distance=round(distance, 4),
            explanation=self._explain(raw, similarity, credibility),
            is_synthetic=bool(raw["is_synthetic"]),
            min_order_qty=int(raw.get("min_order_qty") or 0),
        )

    def _explain(self, buyer: dict[str, Any], similarity: float, cred: float) -> str:
        sim_pct = round(similarity * 100)
        if sim_pct >= 80:
            quality = "sangat tinggi"
        elif sim_pct >= 60:
            quality = "tinggi"
        elif sim_pct >= 40:
            quality = "moderat"
        else:
            quality = "rendah"
        cred_label = "terpercaya" if cred >= 0.7 else "perlu verifikasi lebih lanjut"
        hs_str = ", ".join(buyer["hs_codes"][:3]) if buyer["hs_codes"] else "—"
        return (
            f"Kesesuaian produk {sim_pct}% ({quality}). "
            f"Pembeli dari {buyer['country']} ini dinilai {cred_label} "
            f"(skor kredibilitas {round(cred * 100)}%). "
            f"Aktif mengimpor kategori: {hs_str}."
        )