"""Buyer matching engine — pgvector ANN + credibility-weighted reranking."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import structlog
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

log = structlog.get_logger(__name__)


@dataclass
class MatchRequest:
    product_id: str
    product_description: str
    hs_code: str | None
    moq: int
    top_k: int = 10
    country_filter: list[str] | None = None


@dataclass
class BuyerMatch:
    buyer_id: str
    name: str
    country: str
    hs_codes: list[str]
    credibility_score: float
    similarity_score: float
    distance: float
    explanation: str
    is_synthetic: bool


class MatchingService:
    """
    Pipeline:
      1) Load product embedding from product_embedding (generated by embedding-worker)
      2) pgvector ANN search via <=> (cosine distance)
      3) Apply metadata filters (HS code, country, MOQ)
      4) Final score = 0.7 × similarity + 0.3 × credibility
      5) Generate Indonesian explanation per match
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def find_buyers(self, request: MatchRequest) -> list[BuyerMatch]:
        log.info("matching.search.start", product_id=request.product_id, top_k=request.top_k)

        embedding = await self._load_product_embedding(request.product_id)
        if embedding is None:
            log.warning("matching.no_embedding", product_id=request.product_id)
            return []

        rows = await self._ann_search(embedding, request)
        results = [self._enrich(r) for r in rows][: request.top_k]
        log.info("matching.search.done", product_id=request.product_id, found=len(results))
        return results

    async def _load_product_embedding(self, product_id: str) -> list[float] | None:
        result = await self._session.execute(
            text("SELECT embedding FROM product_embedding WHERE product_id = :pid"),
            {"pid": product_id},
        )
        row = result.fetchone()
        return list(row[0]) if row else None

    async def _ann_search(
        self,
        query_embedding: list[float],
        request: MatchRequest,
    ) -> list[dict[str, Any]]:
        params: dict[str, Any] = {
            "q": query_embedding,
            "k": request.top_k * 3,  # over-fetch for post-filter
        }
        hs_clause = ""
        country_clause = ""
        if request.hs_code:
            hs_clause = "AND :hs_code = ANY(b.hs_codes)"
            params["hs_code"] = request.hs_code
        if request.country_filter:
            country_clause = "AND b.country = ANY(:countries)"
            params["countries"] = request.country_filter

        sql = text(f"""
            SELECT
                b.id              AS buyer_id,
                b.name            AS name,
                b.country         AS country,
                b.hs_codes        AS hs_codes,
                b.credibility_score AS credibility_score,
                b.is_synthetic    AS is_synthetic,
                (be.embedding <=> :q) AS distance
            FROM buyer_embedding be
            JOIN buyer b ON b.id = be.buyer_id
            WHERE b.is_active = TRUE
                {hs_clause}
                {country_clause}
            ORDER BY be.embedding <=> :q
            LIMIT :k
        """)
        rows = (await self._session.execute(sql, params)).mappings().all()
        return [dict(r) for r in rows]

    def _enrich(self, raw: dict[str, Any]) -> BuyerMatch:
        distance = float(raw["distance"])
        similarity = 1.0 - distance
        credibility = float(raw["credibility_score"])
        # Final score: 70% similarity + 30% credibility
        final = (similarity * 0.7) + (credibility * 0.3)
        return BuyerMatch(
            buyer_id=str(raw["buyer_id"]),
            name=raw["name"],
            country=raw["country"],
            hs_codes=list(raw["hs_codes"]),
            credibility_score=round(credibility, 3),
            similarity_score=round(final, 4),
            distance=round(distance, 4),
            explanation=self._explain(raw, similarity, credibility),
            is_synthetic=bool(raw["is_synthetic"]),
        )

    def _explain(self, buyer: dict[str, Any], similarity: float, cred: float) -> str:
        sim_pct = round(similarity * 100)
        if sim_pct >= 80:
            quality = "sangat tinggi"
        elif sim_pct >= 60:
            quality = "tinggi"
        elif sim_pct >= 40:
            quality = "moderat"
        else:
            quality = "rendah"
        cred_label = "terpercaya" if cred >= 0.7 else "perlu verifikasi lebih lanjut"
        hs_str = ", ".join(buyer["hs_codes"][:3]) if buyer["hs_codes"] else "—"
        return (
            f"Kesesuaian produk {sim_pct}% ({quality}). "
            f"Pembeli dari {buyer['country']} ini dinilai {cred_label} "
            f"(skor kredibilitas {round(cred * 100)}%). "
            f"Aktif mengimpor kategori: {hs_str}."
        )